"""Daily Brief — physician-quality narrative generated by Claude."""
import json
from datetime import datetime, timezone, timedelta
from sqlalchemy.orm import Session
from sqlalchemy import func

from .client import call_claude, SAFETY_FOOTER
from ..models.health_metric import HealthMetric
from ..models.event import Event
from ..models.intelligence import Pattern, Whisper


def _gather_context(db: Session, user_id: str) -> dict:
    now = datetime.now(timezone.utc)
    d1  = now - timedelta(days=1)
    d7  = now - timedelta(days=7)
    d30 = now - timedelta(days=30)

    def last(mtype):
        r = (db.query(HealthMetric.value)
               .filter(HealthMetric.user_id == user_id,
                       HealthMetric.metric_type == mtype,
                       HealthMetric.ts >= d1)
               .order_by(HealthMetric.ts.desc()).first())
        return round(r[0], 1) if r else None

    def avg(mtype, since):
        r = (db.query(func.avg(HealthMetric.value))
               .filter(HealthMetric.user_id == user_id,
                       HealthMetric.metric_type == mtype,
                       HealthMetric.ts >= since)
               .first())
        return round(r[0], 1) if r and r[0] else None

    ctx: dict = {
        "today": {
            "hrv":          last("hrv_rmssd"),
            "rhr":          last("rhr"),
            "sleep_h":      round(last("sleep_duration_min") / 60, 1) if last("sleep_duration_min") else None,
            "sleep_eff":    last("sleep_efficiency"),
            "steps":        last("steps"),
            "mood":         last("mood_self"),
            "stress":       last("stress_self"),
            "energy":       last("energy_self"),
            "aqi":          last("aqi"),
        },
        "baselines_30d": {
            "hrv":   avg("hrv_rmssd", d30),
            "rhr":   avg("rhr",       d30),
            "sleep_h": round(avg("sleep_duration_min", d30) / 60, 1) if avg("sleep_duration_min", d30) else None,
            "steps": avg("steps",     d30),
            "mood":  avg("mood_self", d30),
        },
        "active_patterns": [],
        "active_whispers": [],
    }

    # Recent patterns
    pats = (db.query(Pattern)
              .filter(Pattern.user_id == user_id, Pattern.status == "active")
              .order_by(Pattern.discovered_at.desc()).limit(3).all())
    ctx["active_patterns"] = [p.title for p in pats]

    # Active whispers
    whisps = (db.query(Whisper)
               .filter(Whisper.user_id == user_id, Whisper.is_active == True)
               .limit(2).all())
    ctx["active_whispers"] = [w.title for w in whisps]

    return ctx


def generate_brief(db: Session, user_id: str) -> dict:
    ctx = _gather_context(db, user_id)

    system = (
        "You are an empathetic personal physician with full knowledge of your patient's last 30 days of health data. "
        "You write daily health briefs that are warm, specific, and end with one concrete action. "
        "Use second person. Reference actual numbers. Never diagnose. Never use generic platitudes."
    )

    user_msg = (
        f"Today's data snapshot:\n{json.dumps(ctx['today'], indent=2)}\n\n"
        f"30-day baselines:\n{json.dumps(ctx['baselines_30d'], indent=2)}\n\n"
        f"Active patterns: {ctx['active_patterns']}\n"
        f"Active alerts: {ctx['active_whispers']}\n\n"
        "Write a daily health brief: 80–120 words, second person, warm but factual. "
        "Reference at least 2 specific numbers and how they compare to baseline. "
        "End with exactly one specific, actionable recommendation for today.\n\n"
        f"{SAFETY_FOOTER}"
    )

    narrative = call_claude(system, user_msg, max_tokens=400)

    # Extract recommendation (last sentence)
    sentences = [s.strip() for s in narrative.replace("\n", " ").split(". ") if s.strip()]
    recommendation = sentences[-1].rstrip(".") if sentences else ""
    body = ". ".join(sentences[:-1]) + "." if len(sentences) > 1 else narrative

    return {
        "narrative":       narrative,
        "recommendation":  recommendation,
        "date":            datetime.now(timezone.utc).date().isoformat(),
        "key_metrics":     ctx["today"],
        "generated_at":    datetime.now(timezone.utc).isoformat(),
    }
